language: go

go:
    - 1.4
    - 1.5
    - tip

services:
    - rabbitmq
    - redis-server

install:
    - go get github.com/satori/go.uuid
    - go get github.com/streadway/amqp
    - go get github.com/garyburd/redigo/redis
    - go get github.com/stretchr/testify/suite
    - go get github.com/stretchr/testify/assert
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

env:
    - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/ GOMAXPROCS=2

script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

